"""
nexus/mcp_fabric/synthesizer.py
---------------------------------
The Synthesizer Agent writes complete, runnable MCP server code
from a natural-language capability gap description.

This is the core novelty of Nexus: instead of the developer writing
tools for the agent, the AGENT writes the tools itself.

Output: a standalone Python script that:
  - Implements the MCP spec (JSON-RPC 2.0 over stdio)
  - Exposes the requested tools via tools/list + tools/call
  - Can be booted in a subprocess and validated by the Sandbox

Why Python (not TypeScript as in the spec doc):
  - Mac M1 local dev: Python subprocess is instant, no Node.js needed
  - TypeScript would require `npm install` inside the sandbox = slow
  - The MCP protocol is identical — only the implementation language differs
  - TypeScript synthesis can be added later for production deployments

The generated server implements the MCP stdio transport:
  - Reads JSON-RPC requests line-by-line from stdin
  - Writes JSON-RPC responses line-by-line to stdout
  - Handles: initialize, tools/list, tools/call
"""

from __future__ import annotations

import json
from textwrap import dedent

import structlog

from nexus.mcp_fabric.models import (
    MCPServerSpec,
    ServerLanguage,
    ServerStatus,
    SynthesisRequest,
    ToolSpec,
)
from nexus.observability.tracing import traced
from nexus.tools.llm_client import Message, OllamaClient

log = structlog.get_logger(__name__)


# ─────────────────────────────────────────────
# Code template — the LLM fills in the blanks
# ─────────────────────────────────────────────

# A minimal working MCP server in Python that the LLM extends.
# The LLM only needs to write the tool_implementations dict.
MCP_SERVER_TEMPLATE = '''#!/usr/bin/env python3
"""
Auto-generated MCP Server: {server_name}
Generated by Nexus Synthesizer Agent.
Implements: {tool_names}
"""

import json
import sys


# ── Tool implementations (generated) ──────────────────────────
{tool_implementations}
# ──────────────────────────────────────────────────────────────


TOOLS_MANIFEST = {tools_manifest}


def handle_request(request: dict) -> dict:
    method = request.get("method", "")
    req_id = request.get("id")

    if method == "initialize":
        return {{
            "jsonrpc": "2.0", "id": req_id,
            "result": {{
                "protocolVersion": "2024-11-05",
                "capabilities": {{"tools": {{}}}},
                "serverInfo": {{"name": "{server_name}", "version": "1.0.0"}}
            }}
        }}

    elif method == "tools/list":
        return {{
            "jsonrpc": "2.0", "id": req_id,
            "result": {{"tools": TOOLS_MANIFEST}}
        }}

    elif method == "tools/call":
        params = request.get("params", {{}})
        tool_name = params.get("name", "")
        arguments = params.get("arguments", {{}})

        if tool_name not in TOOL_DISPATCH:
            return {{
                "jsonrpc": "2.0", "id": req_id,
                "error": {{"code": -32601, "message": f"Tool not found: {{tool_name}}"}}
            }}

        try:
            result = TOOL_DISPATCH[tool_name](arguments)
            return {{
                "jsonrpc": "2.0", "id": req_id,
                "result": {{"content": [{{"type": "text", "text": str(result)}}]}}
            }}
        except Exception as exc:
            return {{
                "jsonrpc": "2.0", "id": req_id,
                "error": {{"code": -32603, "message": str(exc)}}
            }}

    return {{
        "jsonrpc": "2.0", "id": req_id,
        "error": {{"code": -32601, "message": f"Method not found: {{method}}"}}
    }}


def main():
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            request = json.loads(line)
            response = handle_request(request)
            print(json.dumps(response), flush=True)
        except json.JSONDecodeError as exc:
            error = {{"jsonrpc": "2.0", "id": None,
                      "error": {{"code": -32700, "message": f"Parse error: {{exc}}"}}}}
            print(json.dumps(error), flush=True)
        except Exception as exc:
            error = {{"jsonrpc": "2.0", "id": None,
                      "error": {{"code": -32603, "message": f"Internal error: {{exc}}"}}}}
            print(json.dumps(error), flush=True)


if __name__ == "__main__":
    main()
'''


# ─────────────────────────────────────────────
# LLM prompt for generating tool implementations
# ─────────────────────────────────────────────

SYNTHESIS_SYSTEM_PROMPT = dedent("""
    You are an expert Python developer writing tool implementations for an MCP server.

    You will be given a list of tools to implement. For each tool, write a Python function
    that simulates or implements the described behavior.

    CRITICAL RULES:
    1. Output ONLY a JSON object — no markdown, no explanation, no preamble.
    2. The JSON must have this exact shape:
       {
         "implementations": "...python code as a single string...",
         "dispatch": {"tool_name": "function_name", ...}
       }
    3. The "implementations" string contains all function definitions.
       Each function takes a single dict argument called `args`.
    4. Functions must be SAFE: no os.system, no subprocess, no file writes outside /tmp,
       no network calls to external hosts, no rm/delete operations.
    5. For database/API tools: return realistic mock data (the sandbox has no real DB).
       The function name pattern: impl_{tool_name}(args: dict) -> str
    6. Keep each function under 20 lines.

    Example output for a tool named "query_postgres":
    {
      "implementations": "def impl_query_postgres(args: dict) -> str:\\n    table = args.get('table', 'unknown')\\n    return f'Mock result: SELECT * FROM {table} returned 3 rows'\\n",
      "dispatch": {"query_postgres": "impl_query_postgres"}
    }
""").strip()


class SynthesizerOutput(object):
    """Parsed output from the LLM synthesis call."""
    def __init__(self, implementations: str, dispatch: dict[str, str]) -> None:
        self.implementations = implementations
        self.dispatch = dispatch


# ─────────────────────────────────────────────
# Main synthesizer class
# ─────────────────────────────────────────────

class SynthesizerAgent:
    """
    Uses gemma3 (via Ollama) to write MCP server source code.

    Flow:
        SynthesisRequest
            → LLM generates tool function implementations
            → Template is assembled into complete server code
            → MCPServerSpec returned with source_code populated
    """

    def __init__(self, llm: OllamaClient | None = None) -> None:
        self._llm = llm or OllamaClient(fast=False)

    @traced("nexus.mcp_fabric.synthesizer", "synthesize")
    async def synthesize(self, request: SynthesisRequest) -> MCPServerSpec:
        """
        Synthesize a complete MCP server for the given request.

        Returns MCPServerSpec with status=GENERATED and populated source_code.
        Status is still GENERATED (not MOUNTED) — the Sandbox must validate it first.
        """
        server_name = f"nexus_{request.namespace}_{request.id[:8]}_mcp"
        log.info(
            "Synthesis started",
            server_name=server_name,
            tools=[t.name for t in request.tools],
            language=request.language,
        )

        # If no tools specified in the request, ask the LLM to infer them
        tools = request.tools or await self._infer_tools(request)

        # Generate tool implementations via LLM
        implementations, dispatch = await self._generate_implementations(tools)

        # Build the tools manifest (JSON structure for tools/list response)
        tools_manifest = self._build_tools_manifest(tools)

        # Build the dispatch table string for the template
        dispatch_str = json.dumps(dispatch, indent=4)
        dispatch_code = (
            f"\nTOOL_DISPATCH = {{\n"
            + "\n".join(f'    "{k}": {v},' for k, v in dispatch.items())
            + "\n}\n"
        )

        # Assemble the full server source code
        source_code = MCP_SERVER_TEMPLATE.format(
            server_name=server_name,
            tool_names=", ".join(t.name for t in tools),
            tool_implementations=implementations + dispatch_code,
            tools_manifest=json.dumps(tools_manifest, indent=4),
        )

        spec = MCPServerSpec(
            request_id=request.id,
            server_name=server_name,
            language=ServerLanguage.PYTHON,
            source_code=source_code,
            tools=tools,
            status=ServerStatus.GENERATED,
            namespace=request.namespace,
        )

        log.info(
            "Synthesis complete",
            server_name=server_name,
            tools=spec.tool_names,
            source_lines=len(source_code.splitlines()),
        )
        return spec

    # ── Private helpers ───────────────────────────────────────────

    async def _infer_tools(self, request: SynthesisRequest) -> list[ToolSpec]:
        """
        When the Planner didn't specify tools, ask the LLM to infer
        what tools make sense for the described gap.
        """
        from pydantic import BaseModel as PM
        from nexus.mcp_fabric.models import ToolParameter

        class InferredTool(PM):
            name: str
            description: str
            parameters: list[dict] = []

        class InferredTools(PM):
            tools: list[InferredTool]

        prompt = (
            f"What MCP tools should be created to address this capability gap?\n\n"
            f"Gap: {request.gap_description}\n"
            f"Target system: {request.target_system or 'unknown'}\n\n"
            f"Propose 2-3 specific, useful tools."
        )

        try:
            result = await self._llm.chat_structured(
                messages=[Message(role="user", content=prompt)],
                output_schema=InferredTools,
                system="You are a systems engineer designing MCP tools. "
                       "Output JSON only. Tool names must be snake_case.",
                max_retries=2,
            )
            tools = []
            for t in result.tools[:3]:
                params = [
                    ToolParameter(
                        name=p.get("name", "input"),
                        type=p.get("type", "string"),
                        description=p.get("description", ""),
                    )
                    for p in t.parameters[:4]
                ]
                tools.append(ToolSpec(
                    name=t.name,
                    description=t.description,
                    parameters=params,
                ))
            return tools or self._fallback_tools(request)
        except Exception as exc:
            log.warning("Tool inference failed, using fallback", error=str(exc))
            return self._fallback_tools(request)

    async def _generate_implementations(
        self, tools: list[ToolSpec]
    ) -> tuple[str, dict[str, str]]:
        """
        Ask the LLM to write Python function bodies for each tool.
        Returns (implementations_code_string, dispatch_dict).
        """
        tools_desc = "\n".join(
            f"- {t.name}({', '.join(p.name for p in t.parameters)}): {t.description}"
            for t in tools
        )
        prompt = (
            f"Write Python implementations for these MCP tools:\n\n{tools_desc}\n\n"
            f"Remember: return realistic mock data, keep each function under 20 lines, "
            f"no dangerous operations."
        )

        # Parse as plain JSON since we need raw code strings
        from pydantic import BaseModel as PM

        class ImplOutput(PM):
            implementations: str
            dispatch: dict[str, str]

        try:
            result = await self._llm.chat_structured(
                messages=[Message(role="user", content=prompt)],
                output_schema=ImplOutput,
                system=SYNTHESIS_SYSTEM_PROMPT,
                max_retries=3,
            )
            return result.implementations, result.dispatch
        except Exception as exc:
            log.warning("LLM implementation generation failed, using stubs", error=str(exc))
            return self._stub_implementations(tools)

    def _stub_implementations(
        self, tools: list[ToolSpec]
    ) -> tuple[str, dict[str, str]]:
        """
        Fallback: generate minimal stub implementations without LLM.
        Used when Ollama is unavailable or generation fails.
        """
        lines = []
        dispatch = {}
        for tool in tools:
            fn_name = f"impl_{tool.name}"
            params_list = ", ".join(
                f"'{p.name}'" for p in tool.parameters
            )
            lines.append(f"def {fn_name}(args: dict) -> str:")
            lines.append(f'    """Stub for {tool.name}: {tool.description}"""')
            if tool.parameters:
                lines.append(f"    inputs = {{k: args.get(k) for k in [{params_list}]}}")
                lines.append(f"    return f'Mock result for {tool.name}: {{inputs}}'")
            else:
                lines.append(f"    return 'Mock result for {tool.name}'")
            lines.append("")
            dispatch[tool.name] = fn_name
        return "\n".join(lines), dispatch

    def _build_tools_manifest(self, tools: list[ToolSpec]) -> list[dict]:
        """Build the tools/list JSON structure from ToolSpec objects."""
        manifest = []
        for tool in tools:
            properties = {}
            required = []
            for param in tool.parameters:
                properties[param.name] = {
                    "type": param.type,
                    "description": param.description,
                }
                if param.required:
                    required.append(param.name)

            manifest.append({
                "name": tool.name,
                "description": tool.description,
                "inputSchema": {
                    "type": "object",
                    "properties": properties,
                    "required": required,
                },
            })
        return manifest

    def _fallback_tools(self, request: SynthesisRequest) -> list[ToolSpec]:
        """Emergency fallback: one generic exploration tool."""
        from nexus.mcp_fabric.models import ToolParameter
        return [ToolSpec(
            name="explore_system",
            description=f"Explore the target system: {request.gap_description[:80]}",
            parameters=[
                ToolParameter(name="target", type="string",
                              description="System component to explore"),
            ],
        )]
